// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3mu4QCUmaz3EHSov5y6WwoQv9eifpR4c',
    appId: '1:779776563992:web:d2394dbc98dff0282cdc6d',
    messagingSenderId: '779776563992',
    projectId: 'webcinema-ef730',
    authDomain: 'webcinema-ef730.firebaseapp.com',
    storageBucket: 'webcinema-ef730.firebasestorage.app',
    measurementId: 'G-W9XPBW9EF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq9mgwCXm6W_DbWlN2xOs-4Lj5d_7yzXw',
    appId: '1:779776563992:android:9e925f876f4750482cdc6d',
    messagingSenderId: '779776563992',
    projectId: 'webcinema-ef730',
    storageBucket: 'webcinema-ef730.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCglJ_4aq5x120gxtF4Vhlev5Vbu8OEmKQ',
    appId: '1:779776563992:ios:3ac4fb07767fab1f2cdc6d',
    messagingSenderId: '779776563992',
    projectId: 'webcinema-ef730',
    storageBucket: 'webcinema-ef730.firebasestorage.app',
    iosBundleId: 'com.example.quanlyrapchieuphimHaYenN0332026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCglJ_4aq5x120gxtF4Vhlev5Vbu8OEmKQ',
    appId: '1:779776563992:ios:3ac4fb07767fab1f2cdc6d',
    messagingSenderId: '779776563992',
    projectId: 'webcinema-ef730',
    storageBucket: 'webcinema-ef730.firebasestorage.app',
    iosBundleId: 'com.example.quanlyrapchieuphimHaYenN0332026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3mu4QCUmaz3EHSov5y6WwoQv9eifpR4c',
    appId: '1:779776563992:web:1f40a48d1889f2db2cdc6d',
    messagingSenderId: '779776563992',
    projectId: 'webcinema-ef730',
    authDomain: 'webcinema-ef730.firebaseapp.com',
    storageBucket: 'webcinema-ef730.firebasestorage.app',
    measurementId: 'G-JWP32D62CE',
  );
}
